# fly.toml app configuration file generated for weathered-cherry-3967 on 2023-07-10T12:42:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-cherry-3967"
primary_region = "scl"

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
